export const HEADER_WIDTH = {
  ROW_INDEX: 32,
  ASSET_NAME: 240,
  RUNNING_DATE: 280,
  COUNTRY: 360,
  LANGUAGE: 240,
  MESSAGE: 240,
  URL: 400,
  TAGS: 280,
  PLATFORM: 240,
  PLACEMENT: 240,
  PRIMARY_TEXT: 240,
  HEADLINE: 240,
  DESCRIPTION: 240,
  CAPTION: 280,
  CTA: 200,
  ALIGNMENT: 300,
  FILE: 320,
}

export const headerList = [
  { content: '', width: HEADER_WIDTH.ROW_INDEX, isFixed: true },
  { content: 'Asset Name', width: HEADER_WIDTH.ASSET_NAME, isFixed: true },
  { content: 'Running Date', width: HEADER_WIDTH.RUNNING_DATE, isFixed: false },
  { content: 'Country', width: HEADER_WIDTH.COUNTRY, isFixed: false },
  { content: 'Language', width: HEADER_WIDTH.LANGUAGE, isFixed: false },
  { content: 'Message', width: HEADER_WIDTH.MESSAGE, isFixed: false },
  { content: 'URL', width: HEADER_WIDTH.URL, isFixed: false },
  { content: 'Tags', width: HEADER_WIDTH.TAGS, isFixed: false },
  { content: 'Platform', width: HEADER_WIDTH.PLATFORM, isFixed: false },
  { content: 'Placement', width: HEADER_WIDTH.PLACEMENT, isFixed: false },
  { content: 'Primary Text', width: HEADER_WIDTH.PRIMARY_TEXT, isFixed: false },
  { content: 'Headline', width: HEADER_WIDTH.HEADLINE, isFixed: false },
  { content: 'Description', width: HEADER_WIDTH.DESCRIPTION, isFixed: false },
  { content: 'Caption', width: HEADER_WIDTH.CAPTION, isFixed: false },
  { content: 'CTA', width: HEADER_WIDTH.CTA, isFixed: false },
  { content: 'Alignment of Primary text, Headline, Description & Caption', width: HEADER_WIDTH.ALIGNMENT, isFixed: false },
  { content: 'File', width: HEADER_WIDTH.FILE, isFixed: false },
]
